// CSS variable → Tailwind mapping. Values remain in variables.css.
export default {
  "colors": {
    "blue-50": "var(--color-blue-50)",
    "blue-100": "var(--color-blue-100)",
    "blue-500": "var(--color-blue-500)",
    "blue-600": "var(--color-blue-600)",
    "blue-700": "var(--color-blue-700)",
    "blue-800": "var(--color-blue-800)",
    "steel-500": "var(--color-steel-500)",
    "steel-600": "var(--color-steel-600)",
    "steel-700": "var(--color-steel-700)",
    "neutral-0": "var(--color-neutral-0)",
    "neutral-50": "var(--color-neutral-50)",
    "neutral-100": "var(--color-neutral-100)",
    "neutral-200": "var(--color-neutral-200)",
    "neutral-300": "var(--color-neutral-300)",
    "neutral-400": "var(--color-neutral-400)",
    "neutral-500": "var(--color-neutral-500)",
    "neutral-600": "var(--color-neutral-600)",
    "neutral-700": "var(--color-neutral-700)",
    "neutral-800": "var(--color-neutral-800)",
    "neutral-900": "var(--color-neutral-900)",
    "neutral-950": "var(--color-neutral-950)",
    "bg-canvas": "var(--color-bg-canvas)",
    "bg-surface": "var(--color-bg-surface)",
    "bg-subtle": "var(--color-bg-subtle)",
    "bg-overlay": "var(--color-bg-overlay)",
    "text-primary": "var(--color-text-primary)",
    "text-secondary": "var(--color-text-secondary)",
    "text-tertiary": "var(--color-text-tertiary)",
    "text-disabled": "var(--color-text-disabled)",
    "text-inverse": "var(--color-text-inverse)",
    "text-link": "var(--color-text-link)",
    "border-default": "var(--color-border-default)",
    "border-strong": "var(--color-border-strong)",
    "border-subtle": "var(--color-border-subtle)",
    "border-focus": "var(--color-border-focus)",
    "action-primary": "var(--color-action-primary)",
    "action-primary-hover": "var(--color-action-primary-hover)",
    "action-primary-down": "var(--color-action-primary-down)",
    "action-subtle": "var(--color-action-subtle)",
    "nav-bg-default": "var(--color-nav-bg-default)",
    "nav-bg-hover": "var(--color-nav-bg-hover)",
    "nav-bg-active": "var(--color-nav-bg-active)",
    "nav-text-default": "var(--color-nav-text-default)",
    "nav-text-muted": "var(--color-nav-text-muted)",
    "icon-secondary": "var(--color-icon-secondary)",
    "status-success-text": "var(--color-status-success-text)",
    "status-success-bg": "var(--color-status-success-bg)",
    "status-success-border": "var(--color-status-success-border)",
    "status-success-solid": "var(--color-status-success-solid)",
    "status-info-text": "var(--color-status-info-text)",
    "status-info-bg": "var(--color-status-info-bg)",
    "status-info-border": "var(--color-status-info-border)",
    "status-info-solid": "var(--color-status-info-solid)",
    "status-review-text": "var(--color-status-review-text)",
    "status-review-bg": "var(--color-status-review-bg)",
    "status-review-border": "var(--color-status-review-border)",
    "status-review-solid": "var(--color-status-review-solid)",
    "status-warning-text": "var(--color-status-warning-text)",
    "status-warning-bg": "var(--color-status-warning-bg)",
    "status-warning-border": "var(--color-status-warning-border)",
    "status-warning-solid": "var(--color-status-warning-solid)",
    "status-risk-text": "var(--color-status-risk-text)",
    "status-risk-bg": "var(--color-status-risk-bg)",
    "status-risk-border": "var(--color-status-risk-border)",
    "status-risk-solid": "var(--color-status-risk-solid)",
    "status-error-text": "var(--color-status-error-text)",
    "status-error-bg": "var(--color-status-error-bg)",
    "status-error-border": "var(--color-status-error-border)",
    "status-error-solid": "var(--color-status-error-solid)"
  },
  "spacing": {
    "0": "var(--space-0)",
    "1": "var(--space-1)",
    "2": "var(--space-2)",
    "3": "var(--space-3)",
    "4": "var(--space-4)",
    "5": "var(--space-5)",
    "6": "var(--space-6)",
    "8": "var(--space-8)",
    "10": "var(--space-10)",
    "12": "var(--space-12)",
    "16": "var(--space-16)"
  },
  "borderRadius": {
    "0": "var(--radius-0)",
    "3": "var(--radius-3)",
    "4": "var(--radius-4)",
    "6": "var(--radius-6)",
    "8": "var(--radius-8)",
    "12": "var(--radius-12)",
    "16": "var(--radius-16)",
    "full": "var(--radius-full)"
  },
  "zIndex": {
    "sidebar": "var(--z-sidebar)",
    "header": "var(--z-header)",
    "tabs": "var(--z-tabs)",
    "overlay": "var(--z-overlay)",
    "modal": "var(--z-modal)",
    "toast": "var(--z-toast)"
  },
  "fontFamily": {
    "sans": [
      "var(--font-sans)"
    ],
    "symbol": [
      "var(--font-symbol)"
    ]
  }
}
